### ISSUE TITLE
🇰🇷 Korean Translation Tracker

### ISSUE THREAD

**Issue by 100pearlcent** [dair-ai/Prompt-Engineering-Guide#139]
This issue is to show the progress of the translation into Korean, originally rooted in #90.

## 📝 To-do

C L E A N

## 🙌 Done
- [x] `pages/introduction/*` by @100pearlcent & @Denny-Hwang 
- [x] `pages/techniques/*` by @Denny-Hwang 
- [x] `pages/*` by @Denny-Hwang
- [x] `pages/application/*` by @100pearlcent
- [x] `pages/models/*` by @puhuk
- [x] `pages/risks/*` by @100pearlcent

**Comment by puhuk** [comment]
@Denny-Hwang I'm supposed to finalize by tomorrow :) If it is not possible, let me ask for the assistant.

**Comment by puhuk** [comment]
@100pearlcent 
I update and send PR #119 

* [x]  `chatgpt.kr.mdx`
* [x]  `flan.kr.mdx`
* [x]  `gpt-4.kr.mdx`
* [x]   `_meta.kr.json`
* [x]  `llama.kr.mdx`
* [x]  `collection.kr.mdx`

**Comment by 100pearlcent** [comment]
Thanks for updating @Denny-Hwang , @puhuk!
I also have just finished my part and wanna share with you guys PR#108. 

수고하셨습니다 !

**Comment by omarsar** [comment]
Amazing work, team! Thanks for all your efforts and partnership. Korean translation is now live! https://www.promptingguide.ai/kr

Feel free to review it when you get a chance. 

Feel free to share with your friends and your social media. If you share on Twitter or LinkedIn, feel free to tag or share with me there so I can share.

**Comment by 100pearlcent** [comment]
Dear @omarsar 

While flicking thru the part that I took part in, I noticed that enhancement might be needed.
I'd like to keep updating and enhancing the quality of my words.

Anyway this is my very first contribute thing ever in my life and so glad to be part of it. thx.
