### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by Denny-Hwang** [dair-ai/Prompt-Engineering-Guide#90]
Hi~

I would like to contribute to translating this repo into Korean.
I have experience contributing to open source translations and would like to help make LLM useful to more people.

Thank you. Please confirm.

**Comment by omarsar** [comment]
@Denny-Hwang Thanks for your interest in helping with translation. To translate the content into Korean, you can simply create a `ko-pages` folder in the root. You can then translate all the `<>.en.mdx` files found in the pages folder and make sure to keep the same folder structure in your `ko-pages` folder. In other words, don't touch the pages folder since your translated files will all be in the `ko-pages` folder. Once you finish with the translations, you can submit PR and I will take care of integrating it into the website. Does this work for you?

I suggest also using a grammar tool that works for your language to make sure grammar is consistent and avoid spelling errors in your translations. Looking forward to your contributions and thanks a lot. Let me know if you have any questions.

**Comment by omarsar** [comment]
@Denny-Hwang Any update on this? Just wanted to bring your attention some translations I saw in this PR: #108

**Comment by 100pearlcent** [comment]
Hi, @Denny-Hwang!
First of all, I am sorry for interrupting(?) and I feel glad to join this translation with you.
Just wanna let you know that I've just finished the translation for `pages/introduction/*` directory.
I may keep updating this translation almost every day til it's all finished.
You can track my traces on PR #108.
I'm pretty new to this AI thing so your advice always is welcomed!

**Comment by Denny-Hwang** [comment]
Hi @100pearlcent ,
Byulmalsseumulyo.
Thanks for your contributions and very welcome!

I am translating 'technics' chapter now.
You can translating what you want.

Let's translate all documents roughly, then fix in detail. 

One thing I recommend is, when you met some word is hard to translating in Korean, then just use the original word(English).

Thanks you!!

**Comment by omarsar** [comment]
@Denny-Hwang @100pearlcent Please let me know when the PRs are ready to review. 

It would be better to have most of it translated before I can merge. Just ping me here. Thanks for all your efforts. Excited about this.

**Comment by puhuk** [comment]
@100pearlcent , @Denny-Hwang 
Hi, is that ok for me to translate `models`

**Comment by 100pearlcent** [comment]
Dear all Korean fellows,
I've just summed up the list for the folders under `pages`.
So please make sure to mark up the lists you've finished so that we can see our progress at a glance.

## To-do

- [ ] `pages/application` (assigned to @100pearlcent)
  - [x] `_meta.kr.json`
  - [x] `generating.kr.mdx`
  - [x] `pal.kr.mdx`
  - [ ] workplace_casestudy.kr.mdx
- [ ] `pages/models` (assigned to @puhuk)
  - [ ]  `_meta.kr.json`
  - [ ] `chatgpt.kr.mdx`
  - [ ] `flan.kr.mdx`
  - [ ] `gpt-4.zh.mdx`
  - [ ] `llama.kr.mdx`
- [ ] `pages/risks` (assigned to @100pearlcent)
  - [ ]  `_meta.kr.json`
  - [ ] `adversarial.kr.mdx`
  - [ ] `biases.kr.mdx`
  - [ ] `factuality.kr.mdx`
- [ ] `pages/techniques` (assigned to @Denny-Hwang )
  - [ ]  `_meta.kr.json`
  - [ ] `activeprompt.kr.mdx`
  - [ ] `ape.kr.mdx`
  - [ ] `consistency.kr.mdx`
  - [ ] `cot.kr.mdx`
  - [ ] `dsp.kr.mdx`
  - [ ] `fewshot.kr.mdx`
  - [ ] `graph.kr.mdx`
  - [ ] `knowledge.kr.mdx`
  - [ ] `multimodalcot.kr.mdx`
  - [ ] `react.kr.mdx`
  - [ ] `zeroshot.kr.mdx`



## Done
- [x] `pages/introduction/*` by @100pearlcent

**Comment by Denny-Hwang** [comment]
@100pearlcent Thanks for your summary!!.

I've done all pages/techniques chapters and other documents in the pages(documents not in specific chapter).

- [X] pages/introduction/* by @Denny-Hwang 
- [X] pages/* by @Denny-Hwang (documents are not included in any chapers)

**Comment by puhuk** [comment]
Thank you! I share my tasks. 
* [x]   `_meta.kr.json`
* [x]  `chatgpt.kr.mdx`
* [ ]  `flan.kr.mdx`
* [ ]  `gpt-4.kr.mdx`
* [ ]  `llama.kr.mdx`
* [ ]  `pages/techniques` (assigned to @Denny-Hwang )

**Comment by 100pearlcent** [comment]
To @Denny-Hwang and @puhuk 

I'm also really eager to let you guys enable using checkboxes but it seems like it is not happening on issue tab I guess?
As far as I know, in the case of PR tab, it is available to check although the ones are made by others. 
Or maybe that case was available cuz I was the one who created PR request template and got the full-access of the organization 🤔
Any solution for this? Thanks in advance.

Anyway I updated your progression on the list above.
Keep up the good work!

**Comment by puhuk** [comment]
Why don't you create new issue? It would be possible for the checkbox inside issue `body`.

**Comment by 100pearlcent** [comment]
To @Denny-Hwang, @omarsar 

May I open a new issue to create the lists so that we can check them up?

I'll reference this thread for sure.

**Comment by 100pearlcent** [comment]
Just created a new issue guys

**Comment by silopolis** [comment]
Hello friends,

Would love to have the Korean team opinion about my TMS setup proposal here #140 :)

TY
J

**Comment by Denny-Hwang** [comment]
@omarsar Please review Korean's translation PR.
Please check my PR and @100pearlcent , @puhuk 
Thanks!

**Comment by 11mLLM** [comment]
@omarsar 

Here is the advanced version of the Korean docs.

[Introduction](https://github.com/dair-ai/Prompt-Engineering-Guide/pull/242)
[Techniques](https://github.com/dair-ai/Prompt-Engineering-Guide/pull/243)
[Applications](https://github.com/dair-ai/Prompt-Engineering-Guide/pull/244)
[Models](https://github.com/dair-ai/Prompt-Engineering-Guide/pull/245) -> deployment error
[Risk & Misuses](https://github.com/dair-ai/Prompt-Engineering-Guide/pull/246)
